// Copyright (c) Stride contributors (https://stride3d.net)
// Distributed under the MIT license. See the LICENSE.md file in the project root for more information.

namespace AssetStore.Core.Models;

/// <summary>
/// Aggregate generated by CI and consumed by the app. See <c>schemas/index-lock.schema.json</c>.
/// </summary>
public sealed record IndexLock
{
    public int SchemaVersion { get; init; } = 1;

    /// <summary>ISO-8601 timestamp, set by the generator (kept as a string for determinism).</summary>
    public required string GeneratedAt { get; init; }

    public IReadOnlyList<IndexedAsset> Assets { get; init; } = [];
}

/// <summary>A single asset entry in the aggregated index.</summary>
public sealed record IndexedAsset
{
    public required string Id { get; init; }

    public required string Repo { get; init; }

    public required AssetManifest Manifest { get; init; }

    public required IndexedVersion Latest { get; init; }

    public IReadOnlyList<IndexedCertifiedVersion> Certified { get; init; } = [];

    /// <summary>One of: ok, warning, error, unavailable.</summary>
    public required string ValidationStatus { get; init; }

    public IReadOnlyList<string> ValidationMessages { get; init; } = [];

    public string? LastValidatedAt { get; init; }
}

/// <summary>The enriched, validated <c>latest</c> version of an asset.</summary>
public sealed record IndexedVersion
{
    public required string Ref { get; init; }

    public required string Commit { get; init; }

    /// <summary>Deterministic SHA-256 of the AssetData/ folder.</summary>
    public required string ContentHash { get; init; }

    /// <summary>Detected from the .csproj (Stride.* PackageReference), or null.</summary>
    public string? DetectedStrideVersion { get; init; }

    /// <summary>Transitive set of resolved dependency ids (deduplicated, cycle-free).</summary>
    public IReadOnlyList<string> ResolvedDependencies { get; init; } = [];

    public long SizeBytes { get; init; }

    public bool Validated { get; init; }
}

/// <summary>An enriched certified version.</summary>
public sealed record IndexedCertifiedVersion
{
    public required string Version { get; init; }

    public string? Tag { get; init; }

    public required string Commit { get; init; }

    public string? ContentHash { get; init; }

    public string? DetectedStrideVersion { get; init; }

    public IReadOnlyList<string> ResolvedDependencies { get; init; } = [];

    public string? CertifiedBy { get; init; }

    public string? CertifiedAt { get; init; }
}
