// Copyright (c) <YEAR> <COPYRIGHT HOLDER>
// Distributed under the MIT license. See the LICENSE.md file in the project root for more information.

namespace AssetStore.Core.Models;

/// <summary>
/// Aggregate generated by CI and consumed by the app. See <c>schemas/index-lock.schema.json</c>.
/// </summary>
public sealed record IndexLock
{
    public int SchemaVersion { get; init; } = 1;

    /// <summary>ISO-8601 timestamp, set by the generator (kept as a string for determinism).</summary>
    public required string GeneratedAt { get; init; }

    public IReadOnlyList<IndexedAsset> Assets { get; init; } = [];
}

/// <summary>A single asset entry in the aggregated index.</summary>
public sealed record IndexedAsset
{
    public required string Id { get; init; }

    public required string Repo { get; init; }

    public required AssetManifest Manifest { get; init; }

    /// <summary>GitHub stargazer count, when known (filled by the bot via the GitHub API).</summary>
    public int? Stars { get; init; }

    public required IndexedVersion Latest { get; init; }

    /// <summary>Released versions discovered from the repo's git tags (author-controlled).</summary>
    public IReadOnlyList<IndexedTagVersion> Versions { get; init; } = [];

    public IReadOnlyList<IndexedCertifiedVersion> Certified { get; init; } = [];

    /// <summary>One of: ok, warning, error, unavailable.</summary>
    public required string ValidationStatus { get; init; }

    public IReadOnlyList<string> ValidationMessages { get; init; } = [];

    public string? LastValidatedAt { get; init; }
}

/// <summary>The enriched, validated <c>latest</c> version of an asset.</summary>
public sealed record IndexedVersion
{
    public required string Ref { get; init; }

    public required string Commit { get; init; }

    /// <summary>Deterministic SHA-256 of the AssetData/ folder.</summary>
    public required string ContentHash { get; init; }

    /// <summary>Detected from the .csproj (Stride.* PackageReference), or null.</summary>
    public string? DetectedStrideVersion { get; init; }

    /// <summary>Target framework(s) read from the .csproj (e.g. net10.0), or null.</summary>
    public string? TargetFramework { get; init; }

    /// <summary>NuGet packages the project references (external dependencies, not store assets).</summary>
    public IReadOnlyList<IndexedPackage> ExternalDependencies { get; init; } = [];

    /// <summary>Transitive set of resolved dependency ids (deduplicated, cycle-free).</summary>
    public IReadOnlyList<string> ResolvedDependencies { get; init; } = [];

    public long SizeBytes { get; init; }
}

/// <summary>A NuGet package the asset references (its external dependency).</summary>
public sealed record IndexedPackage
{
    public required string Name { get; init; }

    public string? Version { get; init; }
}

/// <summary>A released version discovered from a git tag (lightweight: tag → commit).</summary>
public sealed record IndexedTagVersion
{
    /// <summary>Human version label (tag without a leading 'v').</summary>
    public required string Version { get; init; }

    public required string Tag { get; init; }

    public required string Commit { get; init; }
}

/// <summary>An enriched certified version.</summary>
public sealed record IndexedCertifiedVersion
{
    public required string Version { get; init; }

    public string? Tag { get; init; }

    public required string Commit { get; init; }

    public string? ContentHash { get; init; }

    public string? DetectedStrideVersion { get; init; }

    public IReadOnlyList<string> ResolvedDependencies { get; init; } = [];

    public string? CertifiedBy { get; init; }

    public string? CertifiedAt { get; init; }
}
